# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/5fc5aba8-4a39-4900-bbff-89dc25d4b81d/transcription
Content-Type: application/json

{
  "prompt": "Cruel Summer"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "5fc5aba8-4a39-4900-bbff-89dc25d4b81d",
  "temperature": 0.5,
  "prompt": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}